### ISSUE TITLE
data set 

### ISSUE THREAD

**Issue by zihath** [Hrithik2212/Neural-Machine-Translation--English-to-Tamil#1]
Where I can find the dataset link ?

**Comment by Hrithik2212** [comment]
Hi @zihath

The dataset used is a subset of the greater Samanthar dataset , here's the link to the [Dataset](https://www.kaggle.com/datasets/mathurinache/samanantar) 
I have used the en-ta folder in which I have extracted two hundred thousand documents for training and testing 
I hope this is helpful
